# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/generic_repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Build/Install dependencies
          command: |
            pip install virtualenv
            python -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Zip and Upload to S3 bucket w/ metadata
          command: |
            . venv/bin/activate
            git archive -o generic_repo.zip HEAD

            GITHASH=$(git rev-parse HEAD)

            aws s3 cp generic_repo.zip s3://ami-production-dist/generic_repo/ --metadata \
            '{"githash": "'"$GITHASH"'"}'


      - store_artifacts:
          path: test-reports
          destination: test-reports